package com.mynharcorp.model;
// Generated 01/06/2020 05:14:57 PM by Hibernate Tools 4.3.1



/**
 * Camiseta generated by hbm2java
 */
public class Camiseta  implements java.io.Serializable {


     private CamisetaId id;
     private String numero;

    public Camiseta() {
    }

    public Camiseta(CamisetaId id, String numero) {
       this.id = id;
       this.numero = numero;
    }
   
    public CamisetaId getId() {
        return this.id;
    }
    
    public void setId(CamisetaId id) {
        this.id = id;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }




}


