package com.mynharcorp.model;
// Generated 01/06/2020 05:14:57 PM by Hibernate Tools 4.3.1



/**
 * JugadorId generated by hbm2java
 */
public class JugadorId  implements java.io.Serializable {


     private int idJugador;
     private int idEquipo;
     private int idCamiseta;

    public JugadorId() {
    }

    public JugadorId(int idJugador, int idEquipo, int idCamiseta) {
       this.idJugador = idJugador;
       this.idEquipo = idEquipo;
       this.idCamiseta = idCamiseta;
    }
   
    public int getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(int idJugador) {
        this.idJugador = idJugador;
    }
    public int getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }
    public int getIdCamiseta() {
        return this.idCamiseta;
    }
    
    public void setIdCamiseta(int idCamiseta) {
        this.idCamiseta = idCamiseta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JugadorId) ) return false;
		 JugadorId castOther = ( JugadorId ) other; 
         
		 return (this.getIdJugador()==castOther.getIdJugador())
 && (this.getIdEquipo()==castOther.getIdEquipo())
 && (this.getIdCamiseta()==castOther.getIdCamiseta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdJugador();
         result = 37 * result + this.getIdEquipo();
         result = 37 * result + this.getIdCamiseta();
         return result;
   }   


}


