package com.mynharcorp.model;
// Generated 01/06/2020 05:14:57 PM by Hibernate Tools 4.3.1



/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private int id;
     private String nombre;

    public Marca() {
    }

	
    public Marca(int id) {
        this.id = id;
    }
    public Marca(int id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


